In [5]:
#TITULO LABORATORIO 2
#FECHA 22/05/026
#AUTOR HUGO MARTÍNEZ VALLEJO

In [1]:
import pandas as pd

In [2]:
import random

In [3]:
!pip install pandas

Requirement already satisfied: pandas in C:\anaconda3\envs\Laboratorio\Lib\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in C:\anaconda3\envs\Laboratorio\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\anaconda3\envs\Laboratorio\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\anaconda3\envs\Laboratorio\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\anaconda3\envs\Laboratorio\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [4]:
datos = {
    "usuario": ["ana", "pepe", "Luis", "rosita", "carolina", "paco"],
    "edad": [14, 22, 35, 40, 62, 70],
    "ciudad": ["cuitlahuac", "yanga", "atoyac", "paraje", "fortin", "cuichapa"], # <-- ¡Arreglado aquí!
    "compras_realizadas": [5, 10, 1, 2, 15, 3],
    "activo": [True, True, False, True, False, True],  
    "fecha_registro": ["2026-01-10", "2026-05-21", "2026-02-10", "2026-03-11", "2026-04-15", "2026-07-25"]
}

In [5]:
#Creamos el data fram
dfDatos = pd.DataFrame(datos)

In [6]:
dfDatos

    usuario  edad      ciudad  compras_realizadas  activo fecha_registro
0       ana    14  cuitlahuac                   5    True     2026-01-10
1      pepe    22       yanga                  10    True     2026-05-21
2      Luis    35      atoyac                   1   False     2026-02-10
3    rosita    40      paraje                   2    True     2026-03-11
4  carolina    62      fortin                  15   False     2026-04-15
5      paco    70    cuichapa                   3    True     2026-07-25

In [7]:
#Crear el dataFrame de 1000000 de registros
cantidad = 1000000
dfMillon = pd.DataFrame({
    "nombre": [random.choice(dfDatos["usuario"]) for _ in range(cantidad)],
    "edad": [random.randint(18, 80) for _ in range(cantidad)],
    "ciudad": [random.choice(dfDatos["ciudad"]) for _ in range(cantidad)], 
    "compras_realizadas": [random.randint(1, 10) for _ in range(cantidad)],
    "activo": [random.choice(dfDatos["activo"]) for _ in range(cantidad)],
    "fecha_registro": [random.choice(dfDatos["fecha_registro"]) for _ in range(cantidad)]
})

In [10]:
dfMillon.shape

(1000000, 6)

In [9]:
dfMillon.head()

   nombre  edad    ciudad  compras_realizadas  activo fecha_registro
0    Luis    46    paraje                   7    True     2026-03-11
1    paco    54     yanga                   9   False     2026-07-25
2    paco    40  cuichapa                   6    True     2026-05-21
3  rosita    36    fortin                   9    True     2026-01-10
4     ana    52    atoyac                  10    True     2026-01-10

In [11]:
dfMillon.dtypes

nombre                  str
edad                  int64
ciudad                  str
compras_realizadas    int64
activo                 bool
fecha_registro          str
dtype: object

In [14]:
dfMillon.memory_usage(deep=True)

Index                      132
nombre                53833124
edad                   8000000
ciudad                55833516
compras_realizadas     8000000
activo                 1000000
fecha_registro        59000000
dtype: int64

In [15]:
dfMillon.memory_usage(deep=True).sum()/1024**2

np.float64(177.06563186645508)